COUNT_FILES = ["GSE118028_gene_counts.tsv", "GSE118057_gene_counts.txt"]

include: "rules/combine.smk"
include: "rules/heatmap.smk"
include: "rules/mds.smk"
include: "rules/preprocessing.smk"
include: "rules/volcanoplot.smk"

rule all:
    """ final rule """
    input:
        "images/volcanoplot.jpg"
    shell:
        "echo done"
